#pragma once

#include <cstdint>
#include <filesystem>
#include <future>
#include <memory>
#include <unordered_map>
#include <vector>

#include <string/core/job_system.hpp>
#include <string/gpu/descriptor_allocator.hpp>
#include <string/gpu/device.hpp>
#include <string/gpu/residency_manager.hpp>
#include <string/gpu/resource.hpp>
#include <string/gpu/resource_allocator.hpp>
#include <string/vulkan/transfer_batch.hpp>

#include <volk.h>

// libktx: the transcoded BC7 blob per texture (mip levels we stream from).
#include <ktx.h>

namespace string::assets
{

// A texture decoded to RGBA8 on a worker thread, ready for a (single-threaded) GPU upload. The
// pixels carry their own deleter (stb_image's, bound at the decode site) so decode jobs run in
// parallel without an extra copy and this header stays stb-free.
struct decoded_image
{
    std::unique_ptr<uint8_t, void (*)(void*)> pixels{ nullptr, nullptr };
    int width = 0;
    int height = 0;
    VkFormat format = VK_FORMAT_R8G8B8A8_UNORM;
};

// The asset registry's texture pool: owns EVERY content texture's GPU image + bindless slot — the
// streamed KTX2/BC7 set (as a residency_provider driving the registry's residency_manager), the
// stb-decoded whole uploads, and the shared 1x1 white / flat-normal fallbacks. One owner, one
// destructor: the old split (streamer owns KTX images, the render pass owns stb ones) needed a
// set-difference in the pass destructor to know who frees what.
//
// Streaming model (unchanged from the render-side streamer this absorbs): a texture's BC7 image is
// created at full mip count (partially populated) with sampling pinned to its coarsest mip;
// residency drives detail up — "detail" = resident mip levels counted from the coarsest, so
// detail == levels means every level is resident and base_mip = levels - detail = the sampler's
// minLod. No blob is cached: a stream loads the file, records its mip uploads, frees the blob.
// `phys_base` tracks the finest mip physically uploaded (v1 eviction is minLod-only, no reclaim).
class texture_pool final : public ::string::gpu::residency_provider
{
public:
    // Creates the shared fallbacks (1x1 white, 1x1 flat-normal) immediately: their uploads ride
    // the construction-upload flush, and every material resolution needs their slots.
    texture_pool(::string::gpu::resource_allocator& allocator,
                 ::string::gpu::descriptor_table& descriptor_table, string::TransferBatch& transfer);
    ~texture_pool() override;

    texture_pool(const texture_pool&) = delete;
    texture_pool& operator=(const texture_pool&) = delete;

    uint32_t white_slot() const { return white_slot_; }
    uint32_t flat_normal_slot() const { return flat_normal_slot_; }

    struct Registered
    {
        ::string::gpu::resource_id image;
        std::uint32_t slot;         // bindless texture slot (stable for the image's lifetime)
        std::uint32_t min_detail;   // 0 (the pinned coarse floor)
        std::uint32_t max_detail;   // finest (all levels)
        std::uint32_t base_extent;  // max(width, height) of mip 0 — for the coverage LOD heuristic
    };
    // Register a cooked KTX2 by path (data load deferred to the first stream). `srgb` selects the
    // BC7 format variant when the file must be transcoded; an already-BC7 file's own format wins.
    // The caller (the registry) registers the returned image with its residency_manager.
    Registered add(const std::filesystem::path& path, bool srgb);

    // Upload a whole decoded RGBA8 image (the stb fallback path — no streaming, full mip chain
    // generated by blit). Returns the image + its bindless slot; the pool owns the image.
    struct Uploaded { ::string::gpu::resource_id image; std::uint32_t slot; };
    Uploaded add_decoded(const decoded_image& decoded);

    // residency_provider (note: the returned/queried value is an internal token, not a transfer
    // ticket — a stream spans an async file-load phase then a GPU upload phase):
    std::uint64_t stream(::string::gpu::resource_id id, std::uint32_t from_detail, std::uint32_t to_detail) override;
    bool is_complete(std::uint64_t token) override;
    void on_resident(::string::gpu::resource_id id, std::uint32_t detail) override;
    void evict(::string::gpu::resource_id id, std::uint32_t from_detail, std::uint32_t to_detail) override;
    VkDeviceSize cost(::string::gpu::resource_id id, std::uint32_t detail) override;

    // Diagnostics.
    std::size_t count() const { return textures_.size(); }

private:
    struct Texture
    {
        std::filesystem::path path;
        VkFormat format = VK_FORMAT_UNDEFINED;
        std::uint32_t levels = 0;    // total mip levels (== max_detail)
        std::uint32_t width = 0;
        std::uint32_t height = 0;
        ::string::gpu::resource_id image = 0;
        VkImageView view = VK_NULL_HANDLE;
        std::uint32_t slot = 0;

        // Streaming state. phys_base = finest mip index physically uploaded so far (levels = none).
        std::uint32_t phys_base = 0;
        bool loading = false;             // a background file load is in flight
        std::future<ktxTexture2*> future;
        std::uint32_t pending_base = 0;   // finest mip index the in-flight load must upload down to
        std::uint64_t gpu_ticket = 0;
    };

    std::uint64_t upload_levels(Texture& t, ktxTexture2* ktx, std::uint32_t first_level,
                                std::uint32_t last_level);
    static std::uint32_t base_of(const Texture& t, std::uint32_t detail) { return t.levels - detail; }
    // Publish a texture's resident mip range to its bindless slot: swap the image's sampler to the
    // matching minLod, then rebind. Every residency transition (in or out) goes through here.
    void rebind(Texture& t, std::uint32_t detail);
    bool finish_load(Texture& t);

    ::string::gpu::resource_allocator& allocator_;
    ::string::gpu::descriptor_table& descriptor_table_;
    string::TransferBatch& transfer_;

    // Background file-load workers (zstd inflate, and a UASTC->BC7 transcode on the fallback path;
    // keep the I/O + CPU off the render thread).
    ::string::core::job_system load_pool_;

    std::unordered_map<::string::gpu::resource_id, Texture> textures_;
    std::unordered_map<std::uint64_t, ::string::gpu::resource_id> token_to_id_;
    std::uint64_t next_token_ = 1;

    // Whole-uploaded (stb) images + the two fallbacks — owned here, freed in the destructor.
    std::vector<::string::gpu::resource_id> uploaded_;
    ::string::gpu::resource_id white_image_ = 0;
    std::uint32_t white_slot_ = 0;
    ::string::gpu::resource_id flat_normal_image_ = 0;
    std::uint32_t flat_normal_slot_ = 0;
};

}  // namespace string::assets
